# Generated by Django 5.0.6 on 2024-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0002_schools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterField(
            model_name='schools',
            name='Classrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='Level',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='Sponsor',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='Status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
