# Generated by Django 5.0.6 on 2024-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0003_alter_schools_options_alter_schools_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='Level',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='Sponsor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='Status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
